function report = validateTrackerWorkspace(model, options)
%VALIDATETRACKERWORKSPACE Validate the P2 dense kinematic workspace sweep.
%
% IMPORTANT:
%   report.pass means P2 kinematic workspace validation passed.
%   It does NOT mean the complete pre-control gate passed.
%   Collision/interference remains mandatory P3 work.

arguments
    model (1,1) struct
    options.StepDeg (1,1) double {mustBePositive,mustBeFinite} = 5
end

sweep = trackerWorkspaceSweep(model, StepDeg=options.StepDeg);
s = sweep.summary;

tol.rotationOrthogonality = 1e-10;
tol.rotationDeterminant = 1e-10;
tol.homogeneousBottomRow = 1e-12;
tol.rigidBase = 1e-12;
tol.hierarchy = 1e-12;
tol.jointTransport = 1e-11;
tol.axisRadius = 1e-10;
tol.carrier = 1e-12;
tol.endpointClosure = 1e-11;
tol.displayDrift = 1e-12;

checks = struct("name",{}, "pass",{}, "value",{}, "limit",{});
checks(end+1) = makeCheck("all_transforms_finite", ...
    s.allTransformsFinite, double(~s.allTransformsFinite), 0);
checks(end+1) = makeCheck("proper_rotation_orthogonality", ...
    s.maxRotationOrthogonalityError <= tol.rotationOrthogonality, ...
    s.maxRotationOrthogonalityError, tol.rotationOrthogonality);
checks(end+1) = makeCheck("proper_rotation_determinant", ...
    s.maxRotationDeterminantError <= tol.rotationDeterminant, ...
    s.maxRotationDeterminantError, tol.rotationDeterminant);
checks(end+1) = makeCheck("homogeneous_bottom_row", ...
    s.maxHomogeneousBottomRowError <= tol.homogeneousBottomRow, ...
    s.maxHomogeneousBottomRowError, tol.homogeneousBottomRow);
checks(end+1) = makeCheck("B0_fixed", ...
    s.maxB0Error <= tol.rigidBase, ...
    s.maxB0Error, tol.rigidBase);
checks(end+1) = makeCheck("B1_q2_independence", ...
    s.maxB1Q2DependencyError <= tol.hierarchy, ...
    s.maxB1Q2DependencyError, tol.hierarchy);
checks(end+1) = makeCheck("B2_equals_B1_at_q2_zero", ...
    s.maxB2AtZeroQ2Error <= tol.hierarchy, ...
    s.maxB2AtZeroQ2Error, tol.hierarchy);
checks(end+1) = makeCheck("J1_origin_fixed", ...
    s.maxJ1OriginError <= tol.jointTransport, ...
    s.maxJ1OriginError, tol.jointTransport);
checks(end+1) = makeCheck("J1_axis_fixed", ...
    s.maxJ1AxisError <= tol.jointTransport, ...
    s.maxJ1AxisError, tol.jointTransport);
checks(end+1) = makeCheck("J2_origin_transport", ...
    s.maxJ2OriginTransportError <= tol.jointTransport, ...
    s.maxJ2OriginTransportError, tol.jointTransport);
checks(end+1) = makeCheck("J2_axis_transport", ...
    s.maxJ2AxisTransportError <= tol.jointTransport, ...
    s.maxJ2AxisTransportError, tol.jointTransport);
checks(end+1) = makeCheck("q2_does_not_move_J2_origin", ...
    s.maxJ2Q2OriginError <= tol.jointTransport, ...
    s.maxJ2Q2OriginError, tol.jointTransport);
checks(end+1) = makeCheck("q2_does_not_move_J2_axis", ...
    s.maxJ2Q2AxisError <= tol.jointTransport, ...
    s.maxJ2Q2AxisError, tol.jointTransport);
checks(end+1) = makeCheck("B1_distance_to_J1_axis", ...
    s.maxB1AxisRadiusError <= tol.axisRadius, ...
    s.maxB1AxisRadiusError, tol.axisRadius);
checks(end+1) = makeCheck("B2_distance_to_J2_axis", ...
    s.maxB2AxisRadiusError <= tol.axisRadius, ...
    s.maxB2AxisRadiusError, tol.axisRadius);
checks(end+1) = makeCheck("moving_pulley_carrier", ...
    sweep.auxDrive.movingPulleyMetadataPass && ...
    s.maxMovingPulleyCarrierError <= tol.carrier, ...
    s.maxMovingPulleyCarrierError, tol.carrier);
checks(end+1) = makeCheck("fixed_pulley_carrier", ...
    sweep.auxDrive.fixedPulleyMetadataPass && ...
    s.maxFixedPulleyCarrierError <= tol.carrier, ...
    s.maxFixedPulleyCarrierError, tol.carrier);
checks(end+1) = makeCheck("q2_endpoint_transform_closure", ...
    s.maxQ2EndpointTransformError <= tol.endpointClosure, ...
    s.maxQ2EndpointTransformError, tol.endpointClosure);
checks(end+1) = makeCheck("q2_endpoint_origin_closure", ...
    s.maxQ2EndpointOriginError <= tol.endpointClosure, ...
    s.maxQ2EndpointOriginError, tol.endpointClosure);
checks(end+1) = makeCheck("q2_endpoint_axis_closure", ...
    s.maxQ2EndpointAxisError <= tol.endpointClosure, ...
    s.maxQ2EndpointAxisError, tol.endpointClosure);
checks(end+1) = makeCheck("geometry_vertex_counts_unchanged", ...
    s.geometryVertexCountsUnchanged, ...
    double(~s.geometryVertexCountsUnchanged), 0);
checks(end+1) = makeCheck("display_transform_stable", ...
    s.displayTransformDriftError <= tol.displayDrift, ...
    s.displayTransformDriftError, tol.displayDrift);

posePass = ...
    sweep.pose.finiteTransformPass & ...
    sweep.pose.rotationOrthogonalityError <= tol.rotationOrthogonality & ...
    sweep.pose.rotationDeterminantError <= tol.rotationDeterminant & ...
    sweep.pose.homogeneousBottomRowError <= tol.homogeneousBottomRow & ...
    sweep.pose.b0Error <= tol.rigidBase & ...
    sweep.pose.b1Q2DependencyError <= tol.hierarchy & ...
    (isnan(sweep.pose.b2AtZeroQ2Error) | ...
        sweep.pose.b2AtZeroQ2Error <= tol.hierarchy) & ...
    sweep.pose.j1OriginError <= tol.jointTransport & ...
    sweep.pose.j1AxisError <= tol.jointTransport & ...
    sweep.pose.j2OriginTransportError <= tol.jointTransport & ...
    sweep.pose.j2AxisTransportError <= tol.jointTransport & ...
    sweep.pose.j2Q2OriginError <= tol.jointTransport & ...
    sweep.pose.j2Q2AxisError <= tol.jointTransport & ...
    sweep.pose.b1AxisRadiusError <= tol.axisRadius & ...
    sweep.pose.b2AxisRadiusError <= tol.axisRadius & ...
    sweep.pose.movingPulleyCarrierError <= tol.carrier & ...
    sweep.pose.fixedPulleyCarrierError <= tol.carrier;

sweep.pose.pass = posePass;

report.scope = "P2_DENSE_KINEMATIC_WORKSPACE_ONLY";
report.pass = all([checks.pass]) && all(posePass);
report.preControlGatePass = false;
report.safeOperatingEnvelopeFrozen = false;
report.collisionStatus = "PENDING_P3_COLLISION_INTERFERENCE_AUDIT";
report.grid = sweep.grid;
report.checks = checks;
report.summary = sweep.summary;
report.failedPoseCount = nnz(~posePass);
report.failedPoses = sweep.pose(~posePass,:);
report.sweep = sweep;
report.tolerances = tol;
report.assumptions = [ ...
    "P2 validates kinematic/transform behavior only."; ...
    "Configured J1/J2 limits are not yet certified collision-free."; ...
    "Local pulley spin and flexible-belt motion remain unresolved."];
report.nextRequiredPhase = "P3_COLLISION_INTERFERENCE_AUDIT";
report.generatedAt = string(datetime("now", ...
    "TimeZone","local", "Format","yyyy-MM-dd'T'HH:mm:ssXXX"));
end

function check = makeCheck(name, pass, value, limit)
check.name = string(name);
check.pass = logical(pass);
check.value = double(value);
check.limit = double(limit);
end
