function report = validateTrackerModel(model)
%VALIDATETRACKERMODEL Validate a built model against Phase 1 contract gates.

settings = trackerModelSettings();
checks = repmat(struct("name", "", "pass", false, "details", ""), 0, 1);

required = ["meta","frames","components","geometry","groups","joints", ...
    "cadMass","physics","dynamics","source","status"];
present = string(fieldnames(model));
checks(end+1) = makeCheck("TrackerModel public structure", ...
    all(ismember(required, present)), "Required public fields are present.");

schemaPass = string(model.source.manifest.schema_name) == settings.schemas.manifest(1) && ...
    string(model.source.manifest.schema_version) == settings.schemas.manifest(2) && ...
    string(model.source.componentDocument.schema_name) == settings.schemas.components(1) && ...
    string(model.source.componentDocument.schema_version) == settings.schemas.components(2) && ...
    string(model.source.mateDocument.schema_name) == settings.schemas.mates(1) && ...
    string(model.source.mateDocument.schema_version) == settings.schemas.mates(2);
checks(end+1) = makeCheck("CAD Bridge V2 schemas", schemaPass, ...
    "Manifest, components, and mates schemas equal the frozen V2 references.");

counts = model.source.manifest.counts;
massFailures = sum(~arrayfun(@(x) logical(x.mass_properties_assembly_root.available), model.components));
baselinePass = numel(model.components) == settings.baseline.componentCount && ...
    size(model.geometry.triangles_F0, 1) == settings.baseline.triangleCount && ...
    numel(model.source.mateDocument.mates) == settings.baseline.mateCount && ...
    massFailures == settings.baseline.massPropertyFailures && ...
    model.meta.cadSnapshot == settings.baseline.snapshot && ...
    model.meta.cadConfiguration == settings.baseline.configuration && ...
    double(counts.included_parts) == settings.baseline.componentCount;
checks(end+1) = makeCheck("S0_ZERO baseline counts", baselinePass, ...
    sprintf("components=%d, triangles=%d, mates=%d, mass failures=%d", ...
    numel(model.components), size(model.geometry.triangles_F0, 1), ...
    numel(model.source.mateDocument.mates), massFailures));

mapped = [model.groups.B0.instancePaths; model.groups.B1.instancePaths; ...
    model.groups.B2.instancePaths; model.groups.AUX_DRIVE.instancePaths];
cadPaths = string({model.components.instance_path}).';
coveragePass = numel(mapped) == numel(cadPaths) && ...
    numel(unique(mapped)) == numel(mapped) && isempty(setxor(mapped, cadPaths));
checks(end+1) = makeCheck("Component coverage", coveragePass, ...
    sprintf("B0=%d, B1=%d, B2=%d, AUX_DRIVE=%d, unclassified=%d", ...
    numel(model.groups.B0.instancePaths), numel(model.groups.B1.instancePaths), ...
    numel(model.groups.B2.instancePaths), numel(model.groups.AUX_DRIVE.instancePaths), ...
    numel(setdiff(cadPaths, mapped))));

reportedTriangles = sum(double([model.components.triangle_count]));
geometryPass = reportedTriangles == size(model.geometry.triangles_F0, 1) && ...
    all(ismember(unique(model.geometry.componentIndex), double([model.components.component_index])));
checks(end+1) = makeCheck("Geometry/component-index integrity", geometryPass, ...
    sprintf("reported triangles=%d, imported triangles=%d", reportedTriangles, ...
    size(model.geometry.triangles_F0, 1)));

transforms = model.componentTransforms.H_root_from_component;
orthogonalityErrors = zeros(size(transforms,3),1);
determinantErrors = zeros(size(transforms,3),1);
for k = 1:size(transforms,3)
    R = transforms(1:3,1:3,k);
    orthogonalityErrors(k) = norm(R.' * R - eye(3), "fro");
    determinantErrors(k) = abs(det(R) - 1);
end
transformPass = max(orthogonalityErrors) <= settings.tolerance.rotationOrthogonality && ...
    max(determinantErrors) <= settings.tolerance.rotationDeterminant;
checks(end+1) = makeCheck("Component transform sanity", transformPass, ...
    sprintf("max orthogonality error=%.3g, max determinant error=%.3g", ...
    max(orthogonalityErrors), max(determinantErrors)));

inverseError = norm(model.frames.H_F0_from_root * model.frames.H_root_from_F0 - eye(4), "fro");
referenceError = norm(model.frames.H_F0_from_root - ...
    settings.frames.expectedH_F0_from_root, "fro");
f0Pass = inverseError <= settings.tolerance.inverse && referenceError <= settings.tolerance.inverse;
checks(end+1) = makeCheck("Root to F0 conversion", f0Pass, ...
    sprintf("inverse error=%.3g, corrected reference error=%.3g", inverseError, referenceError));

j1 = model.joints.J1.cadEvidence;
j1Pass = model.joints.J1.validated && ...
    j1.maxAngularMismatchDeg <= settings.tolerance.axisAngleDeg && ...
    j1.maxLineDistanceM <= settings.tolerance.axisLineDistanceM && ...
    j1.maxF0AngularMismatchDeg <= settings.tolerance.axisAngleDeg && ...
    j1.maxF0LineDistanceM <= settings.tolerance.axisLineDistanceM;
checks(end+1) = makeCheck("J1 CAD axis and line", j1Pass, ...
    sprintf("F0 angle=%.9g deg, F0 line distance=%.9g mm", ...
    j1.maxF0AngularMismatchDeg, j1.maxF0LineDistanceM * 1e3));

j2 = model.joints.J2.cadEvidence;
j2Pass = model.joints.J2.validated && ...
    j2.maxAngularMismatchDeg <= settings.tolerance.axisAngleDeg && ...
    j2.maxLineDistanceM <= settings.tolerance.axisLineDistanceM && ...
    j2.maxF0AngularMismatchDeg <= settings.tolerance.axisAngleDeg && ...
    j2.maxF0LineDistanceM <= settings.tolerance.axisLineDistanceM;
checks(end+1) = makeCheck("J2 CAD axis and line", j2Pass, ...
    sprintf("F0 angle=%.9g deg, F0 line distance=%.9g mm", ...
    j2.maxF0AngularMismatchDeg, j2.maxF0LineDistanceM * 1e3));

zero = trackerKinematics(model, [0;0]);
zeroError = max([norm(zero.H_B0-eye(4),"fro"), norm(zero.H_B1-eye(4),"fro"), ...
    norm(zero.H_B2-eye(4),"fro")]);
checks(end+1) = makeCheck("Zero-pose geometry transforms", ...
    zeroError <= settings.tolerance.zeroPose, sprintf("max transform error=%.3g", zeroError));

poseA = trackerKinematics(model, [0.2;0]);
poseB = trackerKinematics(model, [0.2;0.3]);
poseQ2 = trackerKinematics(model, [0;0.3]);
hierarchyPass = isequal(poseA.H_B0, eye(4)) && ...
    norm(poseA.H_B1 - poseB.H_B1, "fro") <= 1e-14 && ...
    norm(poseA.H_B1 - eye(4), "fro") > 1e-6 && ...
    norm(poseQ2.H_B1 - eye(4), "fro") <= 1e-14 && ...
    norm(poseQ2.H_B2 - eye(4), "fro") > 1e-6;
checks(end+1) = makeCheck("Rigid-body motion hierarchy", hierarchyPass, ...
    "B0 fixed; B1 responds only to J1; B2 responds to J1 and J2.");

limitPass = model.joints.J1.qMin == deg2rad(-100) && model.joints.J1.qMax == deg2rad(100) && ...
    model.joints.J2.qMin == deg2rad(-180) && model.joints.J2.qMax == deg2rad(180);
checks(end+1) = makeCheck("Frozen joint ranges", limitPass, ...
    "q1=[-100,100] deg and q2=[-180,180] deg; commands use radians.");

comB1 = model.joints.J1.origin_F0 + model.frames.R01_0 * model.physics.B1.r_O1C1_F1;
comB2 = model.joints.J2.origin_F0 + model.frames.R02_0 * model.physics.B2.r_O2C2_F2;
inertiaB1 = model.frames.R01_0 * model.physics.B1.Ic_F1 * model.frames.R01_0.';
inertiaB2 = model.frames.R02_0 * model.physics.B2.Ic_F2 * model.frames.R02_0.';
physicsInvariant = norm(comB1 - model.physics.invarianceReference.B1.com_F0) <= 1e-12 && ...
    norm(comB2 - model.physics.invarianceReference.B2.com_F0) <= 1e-12 && ...
    norm(inertiaB1 - model.physics.invarianceReference.B1.Ic_F0, "fro") <= 1e-12 && ...
    norm(inertiaB2 - model.physics.invarianceReference.B2.Ic_F0, "fro") <= 1e-12;
massPass = numel(model.cadMass.components) == numel(model.components) && ...
    massFailures == 0 && model.physics.B1.mass == 0.60257 && ...
    model.physics.B2.mass == 0.30680 && physicsInvariant;
checks(end+1) = makeCheck("CAD mass reference and frozen physics separation", massPass, ...
    "CAD masses remain references; v1.1 body-frame re-expression preserves frozen F0 COM/inertia.");

carrier = model.groups.AUX_DRIVE.carrierMotion;
auxPass = contains(model.status, "Local pulley spin") && ...
    string(model.groups.AUX_DRIVE.motionPolicy) == ...
        "carrier_resolved_relative_drive_unresolved" && ...
    isequal(string({carrier.component}), ["GT2_16T-1","GT2_16T-2"]) && ...
    isequal(string({carrier.carrierGroup}), ["B1","B0"]) && ...
    all([carrier.maxAxisAngleDeg] <= settings.tolerance.axisAngleDeg) && ...
    all([carrier.axisLineDistanceM] <= settings.tolerance.axisLineDistanceM);
checks(end+1) = makeCheck("AUX_DRIVE carrier motion", auxPass, model.status);

[displayTransform, displayInfo] = trackerDisplayTransform(model);
displayPass = model.display.framePolicy == "GROUND_ALIGNED_DISPLAY_ONLY" && ...
    isequal(model.display.hiddenBelts, settings.display.hiddenBelts) && ...
    norm(displayInfo.upAxisDisplay - [0;0;1]) <= 1e-12 && ...
    abs(displayTransform(3,4) + displayInfo.minimumB0HeightF0) <= 1e-12;
checks(end+1) = makeCheck("Ground-aligned display and belt visibility policy", ...
    displayPass, "Viewer maps F0 +Y to display +Z, grounds B0, and hides only two explicit belt meshes.");

report.pass = all([checks.pass]);
report.checks = checks;
report.assumptions = [ ...
    "The selected export is the accepted S0_ZERO active, unsuppressed, visible 40-part scope."; ...
    "Coordinate System1 supplies the F0 origin; contract v1.1 supplies the validated CAD-datum-to-analytical-F0 rotation."; ...
    "tracker_seed_groups.json is the only semantic classification authority for this baseline."; ...
    "Public q values are radians unless showTracker explicitly receives Units='degrees'."];
report.unresolvedItems = "AUX_DRIVE pulley carrier translation/rotation is resolved; " + ...
    "local pulley spin and flexible-belt deformation remain unresolved.";
report.generatedAt = string(datetime("now", "TimeZone", "local", ...
    "Format", "yyyy-MM-dd'T'HH:mm:ssXXX"));
end

function check = makeCheck(name, pass, details)
check.name = string(name);
check.pass = logical(pass);
check.details = string(details);
end
